test:
  service: Disk
  root: <%= Rails.root.join("storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
amazon:
   service: S3
   access_key_id: ENV['S3_KEY_ID']
   secret_access_key: ENV['S3_SECRET_KEY']
   region: eu-west-1
   bucket: mashat

# Remember not to checkin your GCS keyfile to a repository
#google:
 # service: GCS
 # project: mashat-205712
 # key: ENV['GOOGLE_CREDENTIALS']
  #bucket: imagemashat

# Use rails credentials:edit to set the Azure Storage secret (as azure_storage:storage_access_key)
# microsoft:
#   service: AzureStorage
#   storage_account_name: your_account_name
#   storage_access_key: <%= Rails.application.credentials.dig(:azure_storage, :storage_access_key) %>
#   container: your_container_name

# mirror:
#   service: Mirror
#   primary: local
#   mirrors: [ amazon, google, microsoft ]
